### PR TITLE
fix: add missing type-casting on event_date field

### PR DESCRIPTION
**Pull request by lch88**
**Are you a current Fivetran customer?** 

Yes, I'm Chris Lee from DelightRoom. My title here is Data and Infrastructure Group Lead.

**What change(s) does this PR introduce?** 

This PR add missing type-casting (from string to date) of `event_date` field in `stg_apple_store__sales_subscription_events` model. It ultimately fixes query error of upstream model [`apple_store__subscription_report`](https://github.com/fivetran/dbt_apple_store/blob/main/models/apple_store__subscription_report.sql).

**Did you update the CHANGELOG?** 

- [ ] Yes

I'm not sure that I'm allowed to touch CHANGELOG directly so please let me know if that is needed for this PR.

**Does this PR introduce a breaking change?**

- [Y] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

It might affect materialized downstream models which depend on the fixed `stg_apple_store__sales_subscription_events` model, if there's any.

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

Not yet. I'm not also sure of versioning policy so just checking in the code change first.

**Is this PR in response to a previously created Bug or Feature Request**

- [X] Yes, Issue/Feature [https://github.com/fivetran/dbt_apple_store/issues/8]
- [ ] No 

**How did you test the PR changes?** 

 

- [ ] Buildkite  
- [X] Local (please provide additional testing details below)

I tested the change on my company's real world dataset and with `fivetran/dbt_apple_store` package which ultimately emitted said error. I confirmed that the error is gone.

**Select which warehouse(s) were used to test the PR**
 

- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:sweat_smile:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Review by fivetran-joemarkiewicz — CHANGES_REQUESTED** [review]
Hi @lch88 thanks so much for opening this PR! 🎉 

This change looks good on my end. However, before approving there are a few other updates we need to apply to this branch:
- [ ] Would you be able to increase the index of the package by one patch version (this time it will be `v0.2.1`). You will make the changes in the dbt_project.yml file [here](https://github.com/lch88/dbt_apple_store_source/blob/32e2140146f796817003d5d24eeb4873da50a1ab/dbt_project.yml#L2), and the integration_tests/dbt_project.yml file [here](https://github.com/lch88/dbt_apple_store_source/blob/32e2140146f796817003d5d24eeb4873da50a1ab/integration_tests/dbt_project.yml#L4).
- [ ] Add an entry in the [CHANGELOG](https://github.com/lch88/dbt_apple_store_source/blob/feature/fix-subs-model-type-issue-in-bigquery/CHANGELOG.md) and that details your change, and also don't forget to include yourself as a contributor!

Let me know once those updates are applied and I can give this a re-review and work to integrate into the next release!

**Comment by lch88** [comment]
Hi @fivetran-joemarkiewicz! I made changes as requested. Feel free to ping me if something more should be done!

**Review by fivetran-joemarkiewicz — APPROVED** [review]
@lch88 thank you again so much for working to contribute this fix to the package! Following the updates you applied (and the minor docs regen I committed), these look good to go on my end! 

FYI - we typically have a release freeze on Friday. Therefore, you can most likely expect this to go live on Monday. Thank you again for your contribution! 🎉

**Comment by lch88** [comment]
Thanks! Happy to help 😄
I'll wait for the update!

**Pull request merged**
